---
- hosts: all
  name: Check status of all services
  tasks:
    - name: Gather service facts
      service_facts:

    - name: Print service status
      debug:
        msg: "{{ item.key }} is {{ item.value.state }}"
      with_dict: "{{ ansible_facts.services }}"
...