#- name: Gather package facts
#  hosts: all
#  tasks:
#    - name: Gather package facts
#      ansible.builtin.package_facts:
#        manager: "{{ ansible_pkg_mgr }}"
#
#    - name: Print package facts
#      debug:
#        var: ansible_facts.packages

---
- name: Gather package information from servers
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get package information
      package_facts:
        manager: auto
