---
- name: Check status of all services
  hosts: all
  tasks:
    - name: Gather service facts
      service_facts:

    - name: Print service status
      debug:
        msg: "{{ item.key }} is {{ item.value.state }}"
      loop: "{{ ansible_facts.services }}"
...