---
- hosts: all
  name: Gather package information from servers
  gather_facts: no
  tasks:
    - name: Get package information
      package_facts:
        manager: auto
      register: packages
      
    - name: Print package facts
      debug:
        var: packages
...
