- name: gather service facts
  hosts: all
  tasks:
    - name: gather service facts
      systemd:
        state: facts
        name: "{{ item }}"
      loop:
        - httpd
        - sshd
      register: services

    - name: Print service facts
      debug:
        var: services
