---
- name: Gather service facts
  hosts: all
  tasks:
    - name: Gather service facts
      service_facts:
        names: 
          - httpd
          - sshd
      register: services

    - name: Print service facts
      debug:
        var: services
...