---
- name: Gather service facts
  hosts: all
  tasks:
    - name: Gather service facts
      service_facts:
        - name: httpd
        - name: sshd
      register: services

    - name: Print service facts
      debug:
        var: services
...