---
- name: Start service
  hosts: ["all"]
  become: true

  vars:
    service_name: nginx

  tasks:
    - name: Check Service
      ansible.builtin.service_facts:

    - name: Start Service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
      when: service_name + '.service' in services